# Generated by Django 3.2.7 on 2021-09-28 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_id'),
        ('greener', '0003_alter_program_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='host',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='authentication.profile'),
        ),
    ]
