# Generated by Django 3.2.7 on 2021-09-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_id'),
        ('greener', '0004_alter_program_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='host',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='authentication.profile'),
        ),
    ]
